spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Validación de constraints de BD al arrancar
spring.jpa.properties.jakarta.persistence.validation.mode=auto

# Paginación por defecto
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

# Clave secreta JWT en Base64
jwt.secret=TWlDbGF2ZVNlY3JldGFTdXBlclNlZ3VyYUNsaW5pY2FQcml2YWRhMjAyNg==
jwt.expiration=86400000