spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.open-in-view=false

spring.jpa.properties.jakarta.persistence.validation.mode=auto

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:4200,http://127.0.0.1:4200,https://clinica-privada-lyart.vercel.app}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=${SPRINGDOC_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRINGDOC_ENABLED:true}
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
